module.exports = {
    purge: [],
    theme: {
        borderRadius: {
            'none': '0',
            'sm': '0.125rem',
            default: '0.25rem',
            default: '4px',
            'md': '0.375rem',
            'lg': '0.5rem',
            'full': '9999px',
            'xl': '1.5rem',
            '2xl': '2.2rem',
            '3xl': '50px',
        },
        fontSize: {
            '4xs': '.38rem',
            '3xs': '.55rem',
            '2xs': '.65rem',
            'xs': '.75rem',
            'sm': '.875rem',
            'tiny': '.875rem',
            'base': '1rem',
            'lg': '1.125rem',
            'xl': '1.25rem',
            '2xl': '1.5rem',
            '3xl': '1.875rem',
            '4xl': '2.25rem',
            '5xl': '3rem',
            '6xl': '4rem',
            '7xl': '5rem',
        },
        extend: {},
    },
    variants: {},
    plugins: [],
}
