module.exports = {
    purge: [],
    theme: {
        borderRadius: {
            'none': '0',
            'sm': '0.125rem',
            default: '0.25rem',
            'md': '0.375rem',
            'lg': '0.5rem',
            'xl': '1rem',
            '2xl': '1.5rem',
            'full': '9999px',
            'large': '12px',
        },
        fontSize: {
            '4xs': '.3rem',
            '3xs': '.4rem',
            '2xs': '.5rem',
            'xs': '.75rem',
            'sm': '.875rem',
            'tiny': '.875rem',
            'base': '1rem',
            'lg': '1.125rem',
            'xl': '1.25rem',
            '2xl': '1.5rem',
            '3xl': '1.875rem',
            '4xl': '2.25rem',
            '5xl': '3rem',
            '6xl': '4rem',
            '7xl': '5rem',
        },
        extend: {},
    },
    variants: {
        textColor: ['responsive', 'hover', 'focus', 'group-hover'],
        opacity: ['responsive', 'hover', 'focus', 'group-hover'],
    },
    plugins: [],
}
